function By = testBy(A, ABC, r, z)

N = @(abc, r, z) abc(1)*r + abc(2)*z + abc(3);

tst = A(1)*N(ABC(:,1), r(1), z(1))/r(1) + ...
    A(2)*N(ABC(:,2), r(2), z(2))/r(2) + ...
    A(3)*N(ABC(:,3), r(3), z(3))/r(3) + ...
    A'*ABC(1,:)';


By = A(1)*N(ABC(:,1), r(1), z(1))/r(1) + ...
    A(2)*N(ABC(:,2), r(2), z(2))/r(2) + ...
    A(3)*N(ABC(:,3), r(3), z(3))/r(3) + ...
    A'*ABC(1,:)';