function sElements = structureElements(elements)

sElements = struct('dim', elements(:,1), ...
                   'regtag', elements(:,3), ...
                   'geotag', elements(:,4), ...
                   'nodes', elements(:,5:end));